project:
  type: website

website:
  title: "Jonas Wallin"
  navbar:
    background: light
    left:
      - text: Publications
        href: publications/index.qmd
        
      - text: Online talks
        href: talks/index.qmd
  page-footer:
    left:
        - text:  "Copyright 2023, Jonas Wallin"
    right:
        - icon: github
          href: "https://github.com/JonasWallin"
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header:
      file: header.html    

editor: visual


execute:
  freeze: auto

bibliography: bib/bibliography.bib
